import = [
    "~/.config/alacritty/themes/themes/breeze.toml"
]
[shell]
program = "/bin/bash"

[font]
size = 12.0


[font.bold]
family = "RobotoMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "RobotoMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "RobotoMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "RobotoMono Nerd font Mono"
style = "Regular"
