# remap prefix to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

#split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# reload config file 
bind r source-file ~/.tmux.conf

# Enable mouse control
set -g mouse on

# don't automatically rename windows
set-option -g allow-rename off

# status bar config
set-option -g status on
set-option -g status-interval 1
set-option -g status-justify centre
set-option -g status-keys vi
set-option -g status-position bottom
set-option -g status-style fg=colour136,bg=colour235
set-option -g status-left-length 20
set-option -g status-left-style default
set-option -g status-left "#[fg=green,bright]#(whoami)#[default]"
set-option -g status-right-length 140
set-option -g status-right-style default
set-option -g status-right "#[fg=green,bg=default,bright]#(tmux-mem-cpu-load -a 0) "
set-window-option -g window-status-style fg=colour244
set-window-option -g window-status-style bg=default
set-window-option -g window-status-current-style fg=colour166
set-window-option -g window-status-current-style bg=default
